theme: jekyll-theme-minimal
logo: https://github.com/slryou41/slryou41.github.io/blob/master/images/IMG_0006.jpg?raw=true
title: [Serim Ryou]
description: [Ph.D. student at Caltech sryou@caltech.edu['mailto: sryou@caltech.edu']]
